version: '3'

services:
  db:
    image: postgres:latest
    container_name: hudson-postgres
    restart: always
    user: postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=hudsondb
      - POSTGRES_PASSWORD=HouseOfTemplates
      - POSTGRES_DB=hudsondb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hudsondb"]
      interval: 1s
      timeout: 5s
      retries: 10


  app:
    build:
      context: .
      dockerfile: dockerfile
    tty: True
    volumes:
      - .:/hudson
    ports:
      - 5000:5000
    command: python hudson/app/app.py